---
path: /home/tihana/Downloads/snakemake_RNA-seq-main/
ID: Scen_control_A
samples_1P:
  - /home/tihana/Downloads/snakemake_RNA-seq-main/Scen1/Scen1_EKDL220016234-1A_HN3NKDSX3_L1_1.SAMPLE_1000.fq.gz
  - /home/tihana/Downloads/snakemake_RNA-seq-main/Scen1/Scen1_EKDL220016234-1A_HN3NKDSX3_L2_1.SAMPLE_1000.fq.gz
  - /home/tihana/Downloads/snakemake_RNA-seq-main/Scen1/Scen1_EKDL220016234-1A_HN3NKDSX3_L3_1.SAMPLE_1000.fq.gz
samples_2P:
  - /home/tihana/Downloads/snakemake_RNA-seq-main/Scen1/Scen1_EKDL220016234-1A_HN3NKDSX3_L1_2.SAMPLE_1000.fq.gz
  - /home/tihana/Downloads/snakemake_RNA-seq-main/Scen1/Scen1_EKDL220016234-1A_HN3NKDSX3_L2_2.SAMPLE_1000.fq.gz
  - /home/tihana/Downloads/snakemake_RNA-seq-main/Scen1/Scen1_EKDL220016234-1A_HN3NKDSX3_L3_2.SAMPLE_1000.fq.gz
genome_assembly: ../../../../media/tihana/16tbdisk/Scen_samples_230207/Dqua.fna
genome_annotation: ../../../../media/tihana/16tbdisk/Scen_samples_230207/Desmodesmus_quadricauda.gtf
adapters: /home/tihana/Downloads/snakemake_RNA-seq-main/illumina_multiplex.fa
